#!/bin/bash
# =============================================================================
# DGX Spark Command Center - One-Command Deployment
# Usage: ./deploy.sh [options]
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
MODE="production"
DGX_SPARK_01_IP="192.168.100.10"
DGX_SPARK_02_IP="192.168.100.11"
SKIP_BUILD=false
DEMO_MODE=false

# =============================================================================
# Help
# =============================================================================
show_help() {
    echo ""
    echo "DGX Spark Command Center - Deployment Script"
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  --node1 IP        IP address of DGX Spark Node 1 (default: 192.168.100.10)"
    echo "  --node2 IP        IP address of DGX Spark Node 2 (default: 192.168.100.11)"
    echo "  --demo            Run in demo mode with simulators (no real hardware needed)"
    echo "  --skip-build      Skip Docker image build (use existing image)"
    echo "  --stop            Stop all services"
    echo "  --logs            Show service logs"
    echo "  --status          Show service status"
    echo "  -h, --help        Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0 --node1 10.0.0.10 --node2 10.0.0.11    Deploy with custom node IPs"
    echo "  $0 --demo                                  Run in demo mode"
    echo "  $0 --stop                                  Stop all services"
    echo ""
}

# =============================================================================
# Parse Arguments
# =============================================================================
while [[ $# -gt 0 ]]; do
    case $1 in
        --node1)
            DGX_SPARK_01_IP="$2"
            shift 2
            ;;
        --node2)
            DGX_SPARK_02_IP="$2"
            shift 2
            ;;
        --demo)
            DEMO_MODE=true
            shift
            ;;
        --skip-build)
            SKIP_BUILD=true
            shift
            ;;
        --stop)
            echo -e "${YELLOW}Stopping DGX Spark Command Center...${NC}"
            docker-compose down
            echo -e "${GREEN}Services stopped.${NC}"
            exit 0
            ;;
        --logs)
            docker-compose logs -f
            exit 0
            ;;
        --status)
            docker-compose ps
            exit 0
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            show_help
            exit 1
            ;;
    esac
done

# =============================================================================
# Banner
# =============================================================================
echo ""
echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                                                                ║${NC}"
echo -e "${BLUE}║     ${GREEN}DGX SPARK COMMAND CENTER${BLUE}                                 ║${NC}"
echo -e "${BLUE}║     ${NC}One-Command Deployment${BLUE}                                    ║${NC}"
echo -e "${BLUE}║                                                                ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# =============================================================================
# Pre-flight Checks
# =============================================================================
echo -e "${YELLOW}[1/5] Running pre-flight checks...${NC}"

# Check Docker
if ! command -v docker &> /dev/null; then
    echo -e "${RED}ERROR: Docker is not installed. Please install Docker first.${NC}"
    exit 1
fi

# Check Docker Compose
if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo -e "${RED}ERROR: Docker Compose is not installed. Please install Docker Compose first.${NC}"
    exit 1
fi

# Check if running as root (needed for port 80)
if [ "$EUID" -ne 0 ] && [ "$DEMO_MODE" = false ]; then
    echo -e "${YELLOW}WARNING: Not running as root. Port 80 may not be accessible.${NC}"
fi

echo -e "${GREEN}  ✓ Docker is installed${NC}"
echo -e "${GREEN}  ✓ Docker Compose is available${NC}"

# =============================================================================
# Configuration
# =============================================================================
echo ""
echo -e "${YELLOW}[2/5] Configuring deployment...${NC}"

# Create .env file
cat > .env << EOF
# DGX Spark Command Center Configuration
# Generated by deploy.sh on $(date)

# DGX Spark Node IPs
DGX_SPARK_01_IP=${DGX_SPARK_01_IP}
DGX_SPARK_02_IP=${DGX_SPARK_02_IP}

# Spark Configuration
SPARK_MASTER_URL=spark://${DGX_SPARK_01_IP}:7077
SPARK_REST_URL=http://${DGX_SPARK_01_IP}:6066
SPARK_UI_URL=http://${DGX_SPARK_01_IP}:8080

# Grafana (optional)
GRAFANA_USER=admin
GRAFANA_PASSWORD=dgxspark

# Alerting (configure these for notifications)
PAGERDUTY_SERVICE_KEY=
SLACK_WEBHOOK_URL=
EOF

echo -e "${GREEN}  ✓ Configuration file created${NC}"
echo "  Node 1: ${DGX_SPARK_01_IP}"
echo "  Node 2: ${DGX_SPARK_02_IP}"

if [ "$DEMO_MODE" = true ]; then
    echo -e "${YELLOW}  ⚡ Demo mode enabled - using simulators${NC}"
fi

# =============================================================================
# Build
# =============================================================================
if [ "$SKIP_BUILD" = false ]; then
    echo ""
    echo -e "${YELLOW}[3/5] Building Docker image...${NC}"
    docker-compose build --no-cache command-center
    echo -e "${GREEN}  ✓ Docker image built successfully${NC}"
else
    echo ""
    echo -e "${YELLOW}[3/5] Skipping build (using existing image)...${NC}"
fi

# =============================================================================
# Deploy
# =============================================================================
echo ""
echo -e "${YELLOW}[4/5] Starting services...${NC}"

if [ "$DEMO_MODE" = true ]; then
    # Start with demo profile (includes simulators)
    docker-compose --profile demo up -d
else
    # Production mode
    docker-compose up -d command-center
fi

# Wait for services to start
echo "  Waiting for services to initialize..."
sleep 10

# =============================================================================
# Verify
# =============================================================================
echo ""
echo -e "${YELLOW}[5/5] Verifying deployment...${NC}"

# Check if container is running
if docker-compose ps | grep -q "Up"; then
    echo -e "${GREEN}  ✓ Container is running${NC}"
else
    echo -e "${RED}  ✗ Container failed to start${NC}"
    echo "  Showing logs:"
    docker-compose logs --tail=50
    exit 1
fi

# Check health endpoint
sleep 5
if curl -sf http://localhost/health > /dev/null 2>&1; then
    echo -e "${GREEN}  ✓ Health check passed${NC}"
else
    echo -e "${YELLOW}  ⚠ Health check pending (services still starting)${NC}"
fi

# =============================================================================
# Success
# =============================================================================
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                                ║${NC}"
echo -e "${GREEN}║     DEPLOYMENT SUCCESSFUL!                                     ║${NC}"
echo -e "${GREEN}║                                                                ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "  Access the Command Center:"
echo -e "    ${BLUE}http://localhost${NC}"
echo ""
echo "  Internal Services:"
echo "    Prometheus:     http://localhost/prometheus/"
if [ "$DEMO_MODE" = true ]; then
    echo "    Spark Simulator: http://localhost:8080"
    echo "    GPU Simulator:   http://localhost:9400/metrics"
fi
echo ""
echo "  Useful Commands:"
echo "    View logs:      ./deploy.sh --logs"
echo "    Check status:   ./deploy.sh --status"
echo "    Stop services:  ./deploy.sh --stop"
echo ""

if [ "$DEMO_MODE" = false ]; then
    echo -e "${YELLOW}  NEXT STEPS:${NC}"
    echo "  1. Run the setup script on each DGX Spark node:"
    echo "     ./scripts/dgx-spark-setup.sh --node-type master  (on node 1)"
    echo "     ./scripts/dgx-spark-setup.sh --node-type worker  (on node 2)"
    echo ""
    echo "  2. Configure alerting in Settings → Integrations"
    echo ""
fi
